function [output] = importXRF_arrays(file)

%scan_type is a string indicating whether the exported csv of interest has
%zeros generated by flyscan mode at Argonee Nat'l lab
%these zzeros must be neglected and should not be imported for purposes
%of performing relevant statistical analyses

A = importdata(file);

for i = 1:size(A.colheaders, 2)
    A.colheaders{i} = genvarname(A.colheaders{i});
    eval(['WORK.  ' A.colheaders{i}  '.raw = A.data(:,i);'])
end
%WORK = data.(scanheader);
WORK.headers = A.colheaders;



%Put the data back into the structure
output   = WORK;
end
